"""
SQL query validator — enforces safety rules before execution.

This is not optional. Every generated SQL query passes through
this validator before execution. No exceptions.

Attack vectors we defend against:
1. Direct mutation: DROP, DELETE, UPDATE, INSERT
2. Prompt injection: user embeds SQL commands in their question
3. Data exfiltration: LIMIT-less queries dumping entire tables
4. Schema probing: queries against system tables
5. Stacked queries: multiple statements in one call
"""
import re

import structlog

logger = structlog.get_logger()

# Statements that mutate data - hard blocked
FORBIDDEN_KEYWORDS = [
    r"\bDROP\b",
    r"\bDELETE\b",
    r"\bUPDATE\b",
    r"\bINSERT\b",
    r"\bALTER\b",
    r"\bCREATE\b",
    r"\bTRUNCATE\b",
    r"\bEXEC\b",
    r"\bMERGE\b",
    r"\bREPLACE\b",
    r"\bEXECUTE\b",
]

# System tables that should never be queried
FORBIDDEN_TABLES = [
    "sqlite_master",
    "sqlite_sequence",
    "information_schema",
    "pg_catalog",
    r"sys\."
]

# Maximum rows we allow any query to return - prevents data dumps
MAX_ROWS_LIMIT = 10_000

class QueryValidationError(Exception):
    """Custom exception for query validation failures."""
    pass

def validate_sql(sql: str) -> str:
    """
    Validate and sanitize a generated SQL query
    Args:
        sql: raw SQL string generated by the LLM

    Returns:
        Cleaned, validated SQL string

    Raises:
        QueryValidationError: if the query fails any safety checks
    """
    # Clean up whitespace for easier regex matching
    sql = sql.strip()

    # Remove markdown fences if LLM wrapped the SQL
    sql = re.sub(r"```(?:sql)?\s*", "", sql).strip()
    sql = sql.rstrip("```").strip()

    # Remove trailing semicolons to prevent stacked queries
    sql = sql.rstrip(";").strip()

    logger.info("validating_query", sql_preview=sql[:100])

    # Rule 1: Must start with SELECT
    if not re.match(r"^SELECT\b", sql, re.IGNORECASE):
        raise QueryValidationError("Only SELECT statements are allowed. Got: " + sql[:50])

    # Rule 2: No forbidden keywords in the query
    sql_upper = sql.upper()
    for pattern in FORBIDDEN_KEYWORDS:
        if re.search(pattern, sql_upper, re.IGNORECASE):
            keyword = re.search(pattern, sql_upper, re.IGNORECASE).group(0)
            raise QueryValidationError(f"Forbidden keyword detected: {keyword}")

    # Rule 3: No queries against forbidden system tables
    for table in FORBIDDEN_TABLES:
        if re.search(rf"\b{table}\b", sql, re.IGNORECASE):
            raise QueryValidationError(f"Querying system tables is not allowed: {table}")

    # Rule 4: No stacked statements (semicolon in the middle of the query)
    if ";" in sql:
        raise QueryValidationError("Multiple statements detected. Only one statement is allowed.")

    # Rule 5: No subquery-based exfiltration patterns (e.g. SELECT * FROM (SELECT * FROM sensitive_table))
    # Catches UNION-based injection attempts as well
    union_pattern = r"\bUNION\b.*\bSELECT\b"
    if re.search(union_pattern, sql, re.IGNORECASE):
        raise QueryValidationError("UNION-based queries are not allowed.")

    # Rule 6: Enforce a maximum row limit to prevent data dumps
    if not re.search(r"\bLIMIT\b", sql, re.IGNORECASE):
        sql = f"{sql} LIMIT {MAX_ROWS_LIMIT}"
        logger.info("enforcing_row_limit", limit=MAX_ROWS_LIMIT)

    logger.info("query_validated")
    return sql
