"""
Unified response model returned by the agentic workflow.
Everything the frontend needs is in one object.
"""

from dataclasses import dataclass, field
from datetime import datetime

from app.agents.intent_classifier import QueryIntent


@dataclass
class AgentResponse:
    """
    Complete response from the agentic workflow.
    Contains all artifacts generated for a user question.
    """

    question: str
    intent: QueryIntent
    success: bool

    # Core outputs
    executive_summary: str = ""
    insights: list[dict] = field(
        default_factory=list
    )  # List of key insights with metadata
    positive_signals: list[str] = field(
        default_factory=list
    )  # list of positive trends or highlights e.g. "Revenue up 10% QoQ"
    risk_factors: list[str] = field(
        default_factory=list
    )  # list of risks or concerns e.g. "Customer churn increased in segment X"
    recommended_actions: list[str] = field(
        default_factory=list
    )  # list of recommended next steps e.g. "Investigate marketing campaign performance in Q2"

    # SQL agent outputs (for sql_query intent)
    sql_query: str = ""  # The SQL query generated by the agent
    sql_results: list[dict] = field(
        default_factory=list
    )  # list of dict rows returned from SQL query
    sql_row_count: int = 0  # Number of rows returned by the SQL query

    # Chart file paths
    chart_paths: dict = field(
        default_factory=dict
    )  # e.g. {"sales_trend": {"png": "path/to/sales_trend.png", "html": "path/to/sales_trend.html"}}

    # Report file paths
    report_paths: dict = field(
        default_factory=dict
    )  # e.g. {"markdown": "path/to/report.md", "pdf": "path/to/report.pdf"}

    # Metadata
    processing_time_ms: int = 0  # Total time taken to process the query
    error: str = ""  # Error message if any step failed
    generated_at: datetime = field(
        default_factory=datetime.now
    )  # Timestamp of when the response was generated

    def to_dict(self) -> dict:
        """Serialize for API response or frontend consumption."""
        return {
            "question": self.question,
            "intent": self.intent.value,
            "success": self.success,
            "executive_summary": self.executive_summary,
            "insights": self.insights,
            "positive_signals": self.positive_signals,
            "risk_factors": self.risk_factors,
            "recommended_actions": self.recommended_actions,
            "sql_query": self.sql_query,
            "sql_results": self.sql_results[:50],  # Limit to first 50 rows for frontend
            "sql_row_count": self.sql_row_count,
            "chart_paths": self.chart_paths,
            "report_paths": self.report_paths,
            "processing_time_ms": self.processing_time_ms,
            "error": self.error,
            "generated_at": self.generated_at.isoformat(),
        }
